name: arm_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  firebase_messaging: ^14.2.1
  flutter_hooks: any
  flutter_animate: any
  freezed_annotation: any
  iconsax: ^0.0.8
  flutter_bloc: ^8.1.3
  http: ^1.2.1
  json_annotation: ^4.8.1
  flutter_screenutil: ^5.5.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: any
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true
